"""add composite index on tasks owner_id and is_completed

Revision ID: 467e50a35721
Revises: e46e9db50f80
Create Date: 2026-08-14 14:47:10.094771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467e50a35721'
down_revision: Union[str, Sequence[str], None] = 'e46e9db50f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_owner_is_completed', 'tasks', ['owner_id', 'is_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_owner_is_completed', table_name='tasks')
    # ### end Alembic commands ###
